name: MacOS

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.rst'
      - 'UNLICENCE'
      - 'Doxyfile.in'
      - 'images/**'
      - 'shaders/**'
  pull_request:
    paths-ignore:
      - '*.rst'
      - 'UNLICENCE'
      - 'Doxyfile.in'
      - 'images/**'
      - 'shaders/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install glad generation requirement
      run: python3 -m pip install --user "Jinja2>=2.7,<4.0"

    - name: Generate
      run: cmake -S"${{ github.workspace }}" -B"${{ github.workspace }}/build" -G Xcode -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"

    - name: Build
      run: cmake --build "${{ github.workspace }}/build" --config ${{ matrix.build_type }}
